version: "3.9"

services:
  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - my-postgres
      - qdrant
    env_file:
      - .env
    networks:
      - mynetwork

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile.app2
    ports:
      - "9001:9001"
    depends_on:
      - my-postgres
      - qdrant
    env_file:
      - .env
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynetwork

  my-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bkkb1234
      POSTGRES_DB: ChatsPasswords
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    networks:
      - mynetwork

volumes:
  postgres_data:
  qdrant_data:

networks:
  mynetwork:
    driver: bridge
