FROM python:3.11.9 



WORKDIR /app  



COPY requirements.txt .    



# Install CPU-only PyTorch first
RUN pip install torch --index-url https://download.pytorch.org/whl/cpu 



RUN pip install -r requirements.txt 


COPY app/all-mpnet-base-v2-local ./app/all-mpnet-base-v2-local



COPY . . 




CMD ["uvicorn", "store_embed:app", "--host", "0.0.0.0", "--port", "9001"]



